version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
      - 8180:8180
      - 9180:9180
    volumes:
      - /tmp/data:/dgraph
    command: dgraph alpha -o 100 --lru_mb 1024 --my=alpha1:7180 --zero=zero1:5180 --logtostderr
      -v=2 --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    deploy:
      resources:
        limits:
          memory: 32G
  alpha2:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha2
    labels:
      cluster: test
    ports:
      - 8182:8182
      - 9182:9182
    volumes:
      - /tmp/data:/dgraph
    command: dgraph alpha -o 102 --lru_mb 1024  --my=alpha2:7182 --zero=zero1:5180 --logtostderr
      -v=2 --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    deploy:
      resources:
        limits:
          memory: 32G
  alpha3:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha3
    labels:
      cluster: test
    ports:
      - 8183:8183
      - 9183:9183
    volumes:
      - /tmp/data:/dgraph
    command: dgraph alpha -o 103 --lru_mb 1024  --my=alpha3:7183 --zero=zero1:5180 --logtostderr
      -v=2 --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    deploy:
      resources:
        limits:
          memory: 32G
  zero1:
    image: dgraph/dgraph:latest
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - 5180:5180
      - 6180:6180
    volumes:
      - /tmp/data:/dgraph
    command: dgraph zero -o 100 --idx=1 --my=zero1:5180 --replicas=3 --logtostderr
      -v=2 --bindall
    deploy:
      resources:
        limits:
          memory: 32G
  zero2:
    image: dgraph/dgraph:latest
    working_dir: /data/zero2
    depends_on:
      - zero1
    labels:
      cluster: test
    ports:
      - 5182:5182
      - 6182:6182
    volumes:
      - /tmp/data:/dgraph
    command: dgraph zero -o 102 --idx=2 --my=zero2:5182 --replicas=3 --logtostderr
      -v=2 --peer=zero1:5180
    deploy:
      resources:
        limits:
          memory: 32G
  zero3:
    image: dgraph/dgraph:latest
    working_dir: /data/zero3
    depends_on:
      - zero2
    labels:
      cluster: test
    ports:
      - 5183:5183
      - 6183:6183
    volumes:
      - /tmp/data:/dgraph
    command: dgraph zero -o 103 --idx=3 --my=zero3:5183 --replicas=3 --logtostderr
      -v=2 --peer=zero1:5180
    deploy:
      resources:
        limits:
          memory: 32G
volumes: {}
